name: prestador_final
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  image_picker: ^0.6.5+3
  animated_splash: ^1.0.0
  flappy_search_bar: ^1.4.1
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+3
  line_icons: ^0.2.0
  rounded_loading_button: ^1.0.4
  email_validator: "0.1.4"
  google_maps_flutter:
  flutter_polyline_points: ^0.1.0
  location: ^2.3.5
  permission_handler: ^3.1.0
  intl: ^0.16.1
  flutter_chat: ^0.1.5
  barcode_scan: ^1.0.0
  awesome_dialog: ^0.1.4
  flutter_country_picker: ^0.1.6
  google_fonts:
  google_map_location_picker: ^3.3.2
  geolocator: any
  stepper_counter_swipe: ^0.0.5
  flutter_webview_plugin: ^0.3.11
  flutter_plugin_pdf_viewer: any
  url_launcher: ^5.4.11
  email_launcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/MR_logo1024px.png" 
  adaptive_icon_background: "assets/MR_logo1024px.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/avisoPrivacidad.pdf
  - data/ayuda.json
  - data/call.json
  - data/servicios.json
  - data/menu_opts.json
  - data/tarjetas.json
  - assets/gatooo.jpg
  - assets/logo_splash.png
  - assets/destination_map_marker.png
  - assets/driving_pin.png
  - assets/friend1.jpg
  - assets/friend2.jpg
  - assets/images/Back.png
  - assets/images/iconoPer.png
  - assets/images/logoMe2.png
  - assets/images/CargaMR.png
  - assets/images/Perfil.png
  - assets/images/logoMe.png
  - assets/images/2.png
  - assets/Espera.gif
  - assets/home/servicios_urgentes/estetoscopio.png
  - assets/home/servicios_urgentes/enfermera.png
  - assets/home/servicios_urgentes/inyeccion.png
  - assets/home/servicios_urgentes/ambulancia.png
  - assets/home/servicios_urgentes/cerrajero.png
  - assets/home/servicios_urgentes/llave.png
  - assets/home/servicios_urgentes/gas.png
  - assets/home/servicios_urgentes/plomeria.png
  - assets/home/servicios_urgentes/grua.png
  - assets/home/servicios_urgentes/ponchadura.png
  - assets/home/servicios_urgentes/gasolina.png
  - assets/home/servicios_urgentes/bateria.png
  - assets/home/servicios_urgentes/pintura.png
  - assets/home/servicios_urgentes/albanil.png
  - assets/home/servicios_urgentes/varios.png
  - assets/home/servicios_urgentes/otros.png
  - assets/home/servicios_urgentes/Veterinario.png
  - assets/home/servicios_urgentes/electrico.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
